kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: growth-hub-nfs-pvc
spec:
  storageClassName: growth-hub-nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
