# requirements.yaml
dependencies:
- name: jupyterhub
  version: '0.9.0'
  repository: 'https://jupyterhub.github.io/helm-chart/'
  import-values:
  - child: rbac
    parent: rbac
- name: nfs-server-provisioner
  version: '~1.0.0'
  repository: 'https://kubernetes-charts.storage.googleapis.com/'
