kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sssc-nfs
spec:
  storageClassName: sssc-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: nfs-code
# spec:
#   storageClassName: nfs
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Mi