apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
data:
  spark-defaults.conf: |-
    spark.kubernetes.namespace={{ .Release.Namespace }}
{{- if index .Values "spark-defaults.conf" -}}
{{ range $key, $value := index .Values "spark-defaults.conf" }}
{{ printf "# %s" $key | indent 4 }}
{{ $value | indent 4 }}
{{- end -}}
{{ end }}
  spark-env.sh: |-
{{- if index .Values "spark-env.sh" -}}
{{ range $key, $value := index .Values "spark-env.sh" }}
{{ printf "# %s" $key | indent 4 }}
{{ $value | indent 4 }}
{{- end -}}
{{ else }}
{{ end }}
  hive-site.xml: |-
{{- if index .Values "hive-site.xml" }}
{{ index .Values "hive-site.xml" | indent 4 }}
{{ else }}
{{ end }}
  log4j.properties: |-
{{- if index .Values "log4j.properties" }}
{{ index .Values "log4j.properties" | indent 4 }}
{{ else }}
{{ end }}
  executor.yaml: |-
{{- if index .Values "executor.yaml" }}
{{ index .Values "executor.yaml" | indent 4 }}
{{ else }}
{{ end }}
  driver.yaml: |-
{{- if index .Values "driver.yaml" }}
{{ index .Values "driver.yaml" | indent 4 }}
{{ else }}
{{ end }}
