apiVersion: v1
name: "genesis-dev"
version: 0.0.2
description: "JupyterHub with Integration for the Astronomy Data Commons tools"
maintainers:
  - name: "Steven Stetzler"
    email: "stevengs@uw.edu"
