# requirements.yaml
dependencies:
- name: aws-hub
  version: '0.0.2'
  repository: 'https://astronomy-commons.github.io/helm-charts/'
  # repository: 'http://127.0.0.1:8879'
  import-values:
  - child: rbac
    parent: rbac
- name: nfs-server-provisioner
  version: '~1.0.0'
  repository: 'https://charts.helm.sh/stable'
